
version: '3.9'

services:

  db:
    image: postgres:12-alpine3.20
    container_name: joke_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - joke_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db 

  app:
    container_name: app_container
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  joke_data: